### PR TITLE
solve openai embedding pkavumba/django-vectordb#5

### PR DESCRIPTION
**Pull request by ahmgam**
error details and solution is this issue #5

### CODE REVIEW

**Comment by pkavumba** [comment]
Fix openai embeddings issue

**Comment by ahmgam** [comment]
excuse me sir, I messed up somthing in the edited file 

please modify this last line (55) from 
```python
        return self.get_embedding(text, self.model)
```
to 
```python
        return self.get_embedding(text)
```
very sorry for this.

**Comment by ahmgam** [comment]
another edit in `utils.py` file , line 107

modify 
```python
    vector = manager.create(
        text=text,
        metadata=metadata,
        embedding=embedding.astype("float32").tobytes(),
        object_id=object_id,
    )
```
to 
```python
    vector = manager.create(
        text=text,
        metadata=metadata,
        embedding=np.array(embedding).astype("float32").tobytes(),
        object_id=object_id,
    )
```

**Comment by pkavumba** [comment]
Thanks will fix it

**Comment by ahmgam** [comment]
@pkavumba 
another error I found while debugging 
modify the file `queryset.py` line 80 from 

```python
query_embeddings = self.model.objects.embedding_fn([text])
```
to 
```python
query_embeddings = self.model.objects.embedding_fn(text)
```
now, everything is working perfectly for OpenAI embeddings!

**Pull request merged**
